import { 
  LayoutGrid, 
  Monitor, 
  ShoppingCart, 
  Smartphone, 
  Sparkles, 
  Paintbrush, 
  PlayCircle, 
  Link as LinkIcon, 
  Zap 
} from "lucide-react";

export const techIcons = {
  "Next.js": { name: "nextjs", color: "#000000" },
  "React": { name: "react", color: "#61DAFB" },
  "TypeScript": { name: "typescript", color: "#3178C6" },
  "JavaScript": { name: "javascript", color: "#F7DF1E" },
  "Python": { name: "python", color: "#3776AB" },
  "Node.js": { name: "nodejs", color: "#339933" },
  "PostgreSQL": { name: "postgresql", color: "#336791" },
  "MySQL": { name: "mysql", color: "#4479A1" },
  "MongoDB": { name: "mongodb", color: "#47A248" },
  "Stripe": { name: "stripe", color: "#635BFF" },
  "Vercel": { name: "vercel", color: "#000000" },
  "OpenAI": { name: "openai", color: "#412991" },
  "FastAPI": { name: "python", color: "#009688" },
  "Docker": { name: "docker", color: "#2496ED" },
  "AWS": { name: "aws", color: "#FF9900" },
  "D3.js": { name: "d3js", color: "#F9A03C" },
  "Figma": { name: "figma", color: "#F24E1E" },
  "Illustrator": { name: "ai", color: "#FF9A00" },
  "Adobe Illustrator": { name: "ai", color: "#FF9A00" },
  "Photoshop": { name: "ps", color: "#31A8FF" },
  "InDesign": { name: "id", color: "#FF3366" },
  "Solidity": { name: "solidity", color: "#363636" },
  "Web3.js": { name: "web3js", color: "#F16822" },
  "IPFS": { name: "ipfs", color: "#65C2CB" },
  "Ethereum": { name: "ethereum", color: "#627EEA" },
  "After Effects": { name: "ae", color: "#9999FF" },
  "Premiere Pro": { name: "pr", color: "#9999FF" },
  "Cinema 4D": { name: "cinema4d", color: "#011A6A" },
  "Audition": { name: "au", color: "#9999FF" },
  "Selenium": { name: "selenium", color: "#43B02A" },
  "TensorFlow": { name: "tensorflow", color: "#FF6F00" },
  "Tailwind": { name: "tailwindcss", color: "#06B6D4" },
  "Framer Motion": { name: "framer", color: "#0055FF" },
  "Analytics": { name: "analytics", color: "#E37400" },
  "Sketch": { name: "sketch", color: "#F7B500" },
  "Lottie": { name: "lottie", color: "#00DDB3" },
  "Laravel": { name: "laravel", color: "#FF2D20" },
  "Vue.js": { name: "vuejs", color: "#4FC08D" },
  "WordPress": { name: "wordpress", color: "#21759B" },
  "WooCommerce": { name: "woocommerce", color: "#96588A" },
  "PHP": { name: "php", color: "#777BB4" },
  "UI/UX": { name: "figma", color: "#F24E1E" },
  "Web Design": { name: "figma", color: "#F24E1E" },
  "mobile": { name: "react", color: "#61DAFB" },
  "Website": { name: "nextjs", color: "#000000" },
};

export const filters = [
  { id: "all", label: "All Work", icon: LayoutGrid },
  { id: "web", label: "Web Development", icon: Monitor },
  { id: "ecommerce", label: "E-commerce", icon: ShoppingCart },
  { id: "mobile", label: "Mobile Development", icon: Smartphone },
  { id: "ai", label: "AI & Machine Learning", icon: Sparkles },
  { id: "design", label: "Design & Branding", icon: Paintbrush },
  { id: "video", label: "Video Production", icon: PlayCircle },
  { id: "blockchain", label: "Web3 & Blockchain", icon: LinkIcon },
  { id: "automation", label: "Automation & Tools", icon: Zap },
];

export const projects = [
  {
    slug: "care-offers-brand-identity-design",
    title: "Care Offers — Brand identity design",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2024",
    link: "https://www.behance.net/gallery/208476371/Care-Offers-Brand-identity-design",
    tech: ["Adobe Illustrator"],
    result: "",
    description: "A complete brand identity design for Care Offers, covering logo, color palette, and visual guidelines.",
    content: "",
    project: {
      banner: "https://i.imgur.com/OeJeLbQ.png",
      images: [
        "https://i.imgur.com/9KsYJi2.png",
        "https://i.imgur.com/RUipZdK.png",
        "https://i.imgur.com/CBk4yoj.png",
        "https://i.imgur.com/iQJDP0j.png",
        "https://i.imgur.com/GsH6FFw.png",
        "https://i.imgur.com/RI74EFe.png",
        "https://i.imgur.com/oczcyaR.png",
        "https://i.imgur.com/3oaxWnx.png",
        "https://i.imgur.com/saWjmxD.png",
        "https://i.imgur.com/1OAaYBj.png",
        "https://i.imgur.com/hW2y1wu.png",
        "https://i.imgur.com/uz6eY8a.png",
        "https://i.imgur.com/sZdOe07.png",
        "https://i.imgur.com/OeJeLbQ.png",
        "https://i.imgur.com/oMpL4B9.png",
        "https://i.imgur.com/VzJXOaw.png",
        "https://i.imgur.com/FvE6cS8.png",
      ],
    },
  },
  {
    slug: "tisura-visual-identity",
    title: "Tisura Visual Identity",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2025",
    link: "https://www.behance.net/gallery/231287631/Tisura-Visual-Identity",
    tech: ["Adobe Illustrator", "Figma"],
    result: "",
    description: "A modern visual identity for Tisura, a technology and Web3 brand, including logo design and brand guidelines.",
    content: "",
    project: {
      banner: "https://i.imgur.com/yS5a0dM.png",
      images: [
        "https://i.imgur.com/dfVASeG.png",
        "https://i.imgur.com/ZOOt55a.png",
        "https://i.imgur.com/c9dnZeS.png",
        "https://i.imgur.com/nrTITOt.png",
        "https://i.imgur.com/zZUnjuc.png",
        "https://i.imgur.com/P0fcHc8.png",
        "https://i.imgur.com/s6aVYfZ.png",
        "https://i.imgur.com/4gNl9EX.png",
      ],
    },
  },
  {
    slug: "sea-breeze-brand-identity",
    title: "Sea breeze brand identity",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2024",
    link: "https://www.behance.net/gallery/196831957/Sea-breeze-brand-identity",
    tech: ["Adobe Illustrator"],
    result: "",
    description: "A fresh and coastal brand identity for Sea Breeze, including logo, typography, and visual identity system.",
    content: "",
    project: {
      banner: "https://i.imgur.com/7RfJVlO.png",
      images: [
        "https://i.imgur.com/dcmVPEd.png",
        "https://i.imgur.com/mt24Asc.png",
        "https://i.imgur.com/ZELcrge.png",
        "https://i.imgur.com/7RfJVlO.png",
        "https://i.imgur.com/9M6tgCd.png",
        "https://i.imgur.com/urESrMI.png",
        "https://i.imgur.com/RmRXJec.png",
        "https://i.imgur.com/kOI35pu.png",
      ],
    },
  },
  {
    slug: "le-roi-de-fajitas-rebranding",
    title: "Le roi de fajitas REBRANDING",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2024",
    link: "https://www.behance.net/gallery/192265295/Le-roi-de-fajitas-REBRANDING",
    tech: ["Adobe Illustrator"],
    result: "",
    description: "Full rebranding for a restaurant chain, including a new logo, social media visuals, and updated marketing materials.",
    content: "",
    project: {
      banner: "https://i.imgur.com/ClOJ8Ao.png",
      images: [
        "https://i.imgur.com/p6ihcDN.png",
        "https://i.imgur.com/gKwDpVe.png",
        "https://i.imgur.com/85xWHl2.png",
        "https://i.imgur.com/jofxm1W.png",
        "https://i.imgur.com/5FbZHrC.png",
        "https://i.imgur.com/qzEuM2H.png",
        "https://i.imgur.com/ClOJ8Ao.png",
        "https://i.imgur.com/KE1YKpc.png",
        "https://i.imgur.com/haci0rT.png",
        "https://i.imgur.com/wQ8tlut.png",
        "https://i.imgur.com/unMEIMn.png",
      ],
    },
  },
  {
    slug: "cosmetics-brand-identity",
    title: "Cosmetics brand identity",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2023",
    link: "https://www.behance.net/gallery/178447283/Cosmetics-brand-identity",
    tech: ["Adobe Illustrator"],
    result: "",
    description: "An elegant cosmetics brand identity featuring logo design, packaging mockups, and a cohesive visual language.",
    content: "",
    project: {
      banner: "https://i.imgur.com/pqTji5z.png",
      images: [
        "https://i.imgur.com/pqTji5z.png",
        "https://i.imgur.com/O8Wftao.png",
        "https://i.imgur.com/SbAp0pQ.png",
        "https://i.imgur.com/hIWw90z.png",
        "https://i.imgur.com/KA3ooZ1.png",
        "https://i.imgur.com/XRHQIHp.png",
        "https://i.imgur.com/VzKpomy.png",
        "https://i.imgur.com/W49CE57.png",
        "https://i.imgur.com/c08qyFt.png",
        "https://i.imgur.com/xCZOCaW.png",
        "https://i.imgur.com/31IhjCu.png",
      ],
    },
  },
  {
    slug: "wegoo-ecommerce-saas-landing-page",
    title: "Wegoo — E‑commerce SaaS Landing Page",
    category: "web",
    service: "web-design",
    github: "",
    year: "2025",
    link: "https://www.behance.net/gallery/237725467/Wegoo-E-commerce-SaaS-Landing-Page",
    tech: ["Figma"],
    result: "",
    description: "A high-converting SaaS landing page UI/UX design for Wegoo, an e-commerce platform, with a modern and clean aesthetic.",
    content: "",
    project: {
      banner: "https://i.imgur.com/GyRF7N7.png",
      images: [
        "https://i.imgur.com/GyRF7N7.png",
        "https://i.imgur.com/mifT1qR.png",
        "https://i.imgur.com/ep7TzGJ.png",
        "https://i.imgur.com/xhWBnoB.png",
        "https://i.imgur.com/fEAdWXQ.png",
        "https://i.imgur.com/4pqdRXq.png",
        "https://i.imgur.com/98D8zG5.png",
        "https://i.imgur.com/2NlnYRn.png",
        "https://i.imgur.com/TbMfQn4.png",
        "https://i.imgur.com/9MYJDEg.png",
        "https://i.imgur.com/kDt1V89.png",
        "https://i.imgur.com/SaBrVRI.png",
        "https://i.imgur.com/Qzmdovo.png",
        "https://i.imgur.com/9d9skfR.png",
        "https://i.imgur.com/6JjTt30.png",
        "https://i.imgur.com/XmmpRxu.png",
        "https://i.imgur.com/6PkIvBE.png",
        "https://i.imgur.com/AVojQWI.png",
        "https://i.imgur.com/ZxErDMk.png",
        "https://i.imgur.com/o7ODfrm.png",
      ],
    },
  },
  {
    slug: "irtaqi-ai-powered-ahkam-learning-app-case-study-ui-ux",
    title: "Irtaqi: AI‑Powered Ahkam Learning App Case Study (UI/UX)",
    category: "mobile",
    service: "ui-ux-design",
    github: "",
    year: "2024",
    link: "https://www.behance.net/gallery/192499395/IrtaqiAI-Powered-Ahkam-Learning-App-Case-Study(UI-UX)",
    tech: ["Figma"],
    result: "",
    description: "A full UI/UX case study for an AI-powered mobile app that helps users learn Quranic Ahkam through interactive lessons.",
    content: "",
    project: {
      banner: "https://i.imgur.com/CBmu0wB.png",
      images: [
        "https://i.imgur.com/CBmu0wB.png",
        "https://i.imgur.com/FWwcXCg.png",
        "https://i.imgur.com/WSfzQnA.png",
        "https://i.imgur.com/Ort1XpC.png",
        "https://i.imgur.com/bcZhEyS.png",
        "https://i.imgur.com/8F7c4GY.png",
        "https://i.imgur.com/H6zM5mX.png",
        "https://i.imgur.com/AfgCF1g.png",
        "https://i.imgur.com/pQ9pVXi.png",
        "https://i.imgur.com/CdDX01r.png",
        "https://i.imgur.com/ojqh5KY.png",
        "https://i.imgur.com/MuaxVmm.png",
        "https://i.imgur.com/uOwaXCE.png",
        "https://i.imgur.com/ve8asOO.png",
        "https://i.imgur.com/We0xUXv.png",
        "https://i.imgur.com/VvYHdGb.png",
        "https://i.imgur.com/tI7X4wu.png",
        "https://i.imgur.com/K0vP0KB.png",
      ],
    },
  },
  {
    slug: "spotifai-website-uiux-case-study",
    title: "SpotifAi — Website UI/UX Case Study",
    category: "web",
    service: "ui-ux-design",
    github: "",
    year: "2023",
    link: "https://www.behance.net/gallery/180562243/SpotifAi-Website-UIUX-Case-Study",
    tech: ["Figma"],
    result: "",
    description: "A UI/UX case study for SpotifAi, an AI-enhanced music streaming web platform with redesigned discovery and listening experiences.",
    content: "",
    project: {
      banner: "https://i.imgur.com/s6QjdLO.png",
      images: [
        "https://i.imgur.com/s6QjdLO.png",
        "https://i.imgur.com/RWpn69Q.png",
        "https://i.imgur.com/XESZE06.png",
        "https://i.imgur.com/6EXO5ce.png",
        "https://i.imgur.com/XAGJecN.png",
        "https://i.imgur.com/9ENBYEN.png",
        "https://i.imgur.com/OuFEHBA.png",
        "https://i.imgur.com/XVYg4N5.png",
        "https://i.imgur.com/sctv40I.png",
        "https://i.imgur.com/ghNDEEF.png",
        "https://i.imgur.com/iyb7oKA.png",
        "https://i.imgur.com/dU2FakN.png",
        "https://i.imgur.com/jWYJ8tD.png",
        "https://i.imgur.com/AgpXZES.png",
        "https://i.imgur.com/0ES820u.png",
        "https://i.imgur.com/KXZSgjy.png",
        "https://i.imgur.com/X3Yl2sz.png",
        "https://i.imgur.com/qSz9Atr.png",
        "https://i.imgur.com/cFgps2F.png",
      ],
    },
  },
  {
    slug: "trading-app-ui-ux-case-study",
    title: "Trading App UI UX Case Study",
    category: "mobile",
    service: "mobile-app-ui-design",
    github: "",
    year: "2023",
    link: "https://www.behance.net/gallery/170009217/Trading-App-UI-UX-Case-Study",
    tech: ["Figma"],
    result: "A modern trading mobile interface focused on usability, quick trade execution, and clear financial data visualization.",
    description: "A UI/UX case study exploring the design of a modern mobile trading platform that simplifies financial trading for beginners while maintaining advanced tools for experienced traders.",
    content: "The project focuses on designing a mobile trading application with a clean dark interface, intuitive navigation, and powerful market visualization tools.",
    project: {
      banner: "https://i.imgur.com/x7YtbOR.png",
      images: [
        "https://i.imgur.com/x7YtbOR.png",
      ],
    },
  },
  {
    slug: "fastshop-store",
    title: "FastShop Store",
    category: "ecommerce",
    service: "ecommerce-development",
    github: "",
    year: "2024",
    link: "https://fastshop.store",
    tech: ["Laravel", "Vue.js", "MySQL", "Tailwind"],
    result: "",
    description: "Professional e-commerce platform for a big Algerian online store with zero commission fees and advanced payment solutions.",
    content: "",
    project: {
      banner: "/ecom-fastshop.jpg",
      images: ["/ecom-fastshop.jpg"],
    },
  },
  {
    slug: "ecoshop-platform",
    title: "EcoShop Platform",
    category: "web",
    service: "web-development",
    github: "https://github.com/m2agency/ecoshop",
    year: "2024",
    link: "https://ecoshop-demo.com",
    tech: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Vercel"],
    result: "",
    description: "Full-stack e-commerce platform with AI-powered recommendations and real-time inventory management.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "chatbot-pro",
    title: "ChatBot Pro",
    category: "ai",
    service: "ai-development",
    github: "",
    year: "2024",
    link: "https://chatbot-pro-demo.com",
    tech: ["Python", "OpenAI", "FastAPI", "React", "Docker"],
    result: "",
    description: "Intelligent customer service chatbot with natural language processing and multi-language support.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "financeflow-dashboard",
    title: "FinanceFlow Dashboard",
    category: "web",
    service: "web-development",
    github: "",
    year: "2024",
    link: "https://financeflow-demo.com",
    tech: ["React", "D3.js", "Node.js", "MongoDB", "AWS"],
    result: "",
    description: "Real-time financial analytics dashboard with interactive charts and automated reporting features.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "brand-identity-suite",
    title: "Brand Identity Suite",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2024",
    link: "",
    tech: ["Figma", "Illustrator", "Photoshop", "InDesign"],
    result: "",
    description: "Complete brand identity package including logo design, color palette, and brand guidelines.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "nft-marketplace",
    title: "NFT Marketplace",
    category: "blockchain",
    service: "blockchain-development",
    github: "https://github.com/m2agency/nft-marketplace",
    year: "2024",
    link: "https://nft-marketplace-demo.com",
    tech: ["Solidity", "Web3.js", "React", "IPFS", "Ethereum"],
    result: "",
    description: "Decentralized NFT trading platform with smart contract integration and gas optimization.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "product-launch-video",
    title: "Product Launch Video",
    category: "video",
    service: "video-production",
    github: "",
    year: "2024",
    link: "https://vimeo.com/product-launch",
    tech: ["After Effects", "Premiere Pro", "Cinema 4D", "Audition"],
    result: "",
    description: "High-impact product launch video with motion graphics and professional voiceover.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "inventory-automation",
    title: "Inventory Automation",
    category: "automation",
    service: "automation-tools",
    github: "",
    year: "2024",
    link: "",
    tech: ["Python", "Selenium", "PostgreSQL", "Docker"],
    result: "",
    description: "Automated inventory management system with real-time tracking and predictive restocking.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "medical-ai-assistant",
    title: "Medical AI Assistant",
    category: "ai",
    service: "ai-development",
    github: "",
    year: "2024",
    link: "",
    tech: ["TensorFlow", "Python", "React", "FastAPI", "MySQL"],
    result: "",
    description: "AI-powered medical diagnosis assistant with image recognition and patient data analysis.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "saas-landing-page",
    title: "SaaS Landing Page",
    category: "web",
    service: "web-development",
    github: "",
    year: "2024",
    link: "https://saas-landing-demo.com",
    tech: ["Next.js", "Tailwind", "Framer Motion", "Analytics"],
    result: "",
    description: "High-converting SaaS landing page with A/B testing and conversion optimization.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "corporate-rebrand",
    title: "Corporate Rebrand",
    category: "design",
    service: "brand-identity-design",
    github: "",
    year: "2024",
    link: "",
    tech: ["Figma", "Sketch", "Illustrator", "InDesign"],
    result: "",
    description: "Complete corporate rebranding including logo, website design, and marketing materials.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "defi-protocol",
    title: "DeFi Protocol",
    category: "blockchain",
    service: "blockchain-development",
    github: "https://github.com/m2agency/defi-protocol",
    year: "2024",
    link: "",
    tech: ["Solidity", "React", "Web3.js", "Ethereum"],
    result: "",
    description: "Decentralized finance protocol with yield farming and liquidity mining features.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "social-media-campaign",
    title: "Social Media Campaign",
    category: "video",
    service: "video-production",
    github: "",
    year: "2024",
    link: "",
    tech: ["After Effects", "Premiere Pro", "Photoshop", "Lottie"],
    result: "",
    description: "Multi-platform social media video campaign with engaging animations and trending formats.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "mobile-health-tracker",
    title: "Mobile Health Tracker",
    category: "mobile",
    service: "mobile-development",
    github: "https://github.com/m2agency/mobile-health-tracker",
    year: "2024",
    link: "https://mobilehealth-demo.com",
    tech: ["React", "React Native", "Node.js", "MongoDB", "Tailwind"],
    result: "",
    description: "Cross-platform mobile app for health tracking, reminders, and analytics.",
    content: "",
    project: {
      banner: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&h=300&fit=crop",
      images: ["https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&h=300&fit=crop"],
    },
  },
  {
    slug: "modiasn-unisex-store",
    title: "Modiasn Unisex Store",
    category: "ecommerce",
    service: "ecommerce-development",
    github: "",
    year: "2024",
    link: "https://modiasn.com",
    tech: ["Laravel", "Vue.js", "MySQL", "Tailwind"],
    result: "",
    description: "Custom e-commerce website for an Algerian unisex fashion store with modern design and seamless shopping experience.",
    content: "",
    project: {
      banner: "/ecom-modiasn.jpg",
      images: ["/ecom-modiasn.jpg"],
    },
  },
  {
    slug: "tjara-multivendor-platform",
    title: "Tjara Multivendor Platform",
    category: "ecommerce",
    service: "ecommerce-development",
    github: "",
    year: "2024",
    link: "https://tjara.com",
    tech: ["Laravel", "Vue.js", "MySQL", "Tailwind"],
    result: "",
    description: "Comprehensive multivendor marketplace platform allowing multiple sellers to list products and customers to buy from various vendors.",
    content: "",
    project: {
      banner: "/ecom-tjara.jpg",
      images: ["/ecom-tjara.jpg"],
    },
  },
  {
    slug: "furniture-ecommerce-store",
    title: "Furniture E-commerce Store",
    category: "ecommerce",
    service: "ecommerce-development",
    github: "",
    year: "2024",
    link: "https://react-ecommerce-v.netlify.app/",
    tech: ["Laravel", "Vue.js", "MySQL", "Tailwind"],
    result: "",
    description: "Algerian online furniture store specializing in tables, chairs, and home furniture with elegant product showcase and smooth checkout.",
    content: "",
    project: {
      banner: "/ecom-noma.jpg",
      images: ["/ecom-noma.jpg"],
    },
  },
  {
    slug: "pink-dream-store",
    title: "Pink Dream Store",
    category: "ecommerce",
    service: "ecommerce-development",
    github: "",
    year: "2024",
    link: "https://pinkdream.store",
    tech: ["WordPress", "WooCommerce", "PHP", "MySQL"],
    result: "",
    description: "Elegant WordPress WooCommerce online store with a dreamy pink aesthetic and optimized shopping experience.",
    content: "",
    project: {
      banner: "/ecom-pinkdream.jpg",
      images: ["/ecom-pinkdream.jpg"],
    },
  },
];

export const getProjectBySlug = (slug) => {
  const project = projects.find((p) => p.slug === slug);
  if (!project) return null;

  // Generate description if it's missing or very short
  if (!project.description || project.description.length < 10) {
    project.description = `Experience the excellence of ${project.title}. This ${project.category} project, developed in ${project.year}, showcases our expertise in ${project.tech.join(", ")}. We delivered a high-quality solution tailored to our client's needs, ensuring professional results and innovative design.`;
  }

  return project;
};
